name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Build ${{ matrix.board_type }}

    strategy:
      matrix:
        include:
          - board_type: FULLSPEC
          - board_type: STANDARD
    steps:
    - uses: actions/checkout@v2
    - uses: pguyot/arm-runner-action@v1
      id: build_image
      with: 
        commands: |
            cd src/raspberrypi
            sudo apt-get update && sudo apt install git libspdlog-dev libpcap-dev genisoimage python3 python3-venv nginx libpcap-dev protobuf-compiler bridge-utils python3-dev libev-dev libevdev2 -y
            make all DEBUG=1 CONNECT_TYPE=${{ matrix.board_type }}
        copy_artifact_path: src/raspberrypi/bin

    # We need to tar the binary outputs to retain the executable
    # file permission. Currently, actions/upload-artifact only
    # supports .ZIP files.
    # This is workaround for https://github.com/actions/upload-artifact/issues/38
    - name: tar binary outputs
      run: tar -czvf rascsi.tar.gz ./bin
      working-directory: ./src/raspberrypi

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: arm-binaries
        path: ./src/raspberrypi/rascsi.tar.gz

#  buildroot-image:
#    runs-on: ubuntu-latest
#    steps:
#      - name: git-fetch buildroot
#        run: git clone git://git.busybox.net/buildroot
#      - name: make defconfig
#        run: make raspberrypi4_defconfig
#        working-directory: ./buildroot
#      - name: make
#        run: make all
#        working-directory: ./buildroot
